[server]
port = 8501
# Habilitar CORS es necesario para la autenticaci贸n con Supabase
enableCORS = true
enableXsrfProtection = true

# Configuraci贸n de autenticaci贸n
browser.gatherUsageStats = false
browser.serverAddress = "localhost"

[theme]
# Usando colores predefinidos para evitar problemas de validaci贸n
base = "light"
primaryColor = "#FF4B4B"  # Rojo
backgroundColor = "#FFFFFF"  # Blanco
secondaryBackgroundColor = "#F0F2F6"  # Gris claro
textColor = "#262730"  # Casi negro
font = "sans serif"
